# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-access-logs-denis-71"
    dynamodb_table = "tf-access-logs-denis-71"
    encrypt        = true
    key            = "terraform.tfstate"
    region         = "us-west-2"
  }
}
