#!/usr/bin/env bash
# Regenerate terragrunt.hcl with a list nested DEPTH levels deep.
# Usage: ./gen.sh [DEPTH]   (default 9500)
set -e
depth="${1:-9500}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 -c "
d=$depth
s='1'
for _ in range(d):
    s='[%s]'%s
open('$here/terragrunt.hcl','w').write('# Generated by gen.sh: a list nested %d levels deep.\n# Run: terragrunt render --json   (hangs, super-linear in nesting depth)\ninputs = { x = %s }\n'%(d,s))
print('wrote terragrunt.hcl at depth', d)
"
