# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "denis-test-tf-state2"
    dynamodb_table = "denis-test-table"
    encrypt        = true
    key            = "./terraform3.tfstate"
    region         = "us-east-1"
  }
}
