# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "s3-test-tg-4"
    dynamodb_table = "s3-test-tg-4"
    encrypt        = true
    key            = "terraform.tfstate3"
    region         = "us-east-1"
  }
}
