# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "test-denis-2024-jenkins-ansible-demo-tf-state"
    dynamodb_table = "jenkins-ansible-demo-lock-table"
    encrypt        = true
    key            = "ansible/terraform.tfstate"
    region         = "us-east-1"
  }
}
