# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
}


provider "databricks" {
  host                        = "databricks_workspace_url"
  azure_workspace_resource_id = "databricks_workspace_id"
}
