# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.2.9"

  required_providers {
    
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.32"
    }
    
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.15"
    }
    
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    
  }
}
