
version: '3'
services:
  terragrunt-engine-server:
    image: terragrunt-engine-server:v1
    environment:
      TOKEN: secret-token
    volumes:
      - /projects:/projects
    ports:
      - "0.0.0.0:50051:50051"
