# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "environment-staging"
    dynamodb_table = "terraform-statefile-locks-staging"
    encrypt        = true
    key            = "staging/terraform.tfstate"
    region         = "us-east-1"
  }
}
