# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket                      = "tg-test-12345"
    impersonate_service_account = "terragrunt2052@tg-tests-341219.iam.gserviceaccount.com"
    prefix                      = "."
  }
}
