# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "environment-development/ec2-instance"
    dynamodb_table = "terraform-statefile-locks-development/ec2-instance"
    encrypt        = true
    key            = "development/ec2-instance/terraform.tfstate"
    region         = "us-east-1"
  }
}
