# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "denis-test-tf-state2222"
    dynamodb_table = "denis-test-table"
    encrypt        = true
    key            = "mysql/terraform.tfstate"
    region         = "ap-northeast-1"
  }
}
