# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "stuff" {
  type = map(string)
}

variable "foo" {
  type = string
}

output "stuff" {
  value = var.stuff
}

output "foo" {
  value = var.foo
}
