# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

variable "aws_tags" {
   type = map
}

provider "aws" {
    region = "us-east-1"
    profile = "prod"
    default_tags {
        tags = var.aws_tags
    }
}

