name: 'terragrunt-init-each-time'

on:
  workflow_dispatch:

env:
  TRACE: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Plan
        uses: gruntwork-io/terragrunt-action@feat/switch-off-docker
        with:
          tf_version: '1.4.6'
          tg_version: 'latest'
          tg_dir: 'terragrunt-init-each-time'
          tg_command: run-all plan

      - name: Apply
        uses: gruntwork-io/terragrunt-action@feat/switch-off-docker
        with:
          tf_version: '1.4.6'
          tg_version: 'latest'
          tg_dir: 'terragrunt-init-each-time'
          tg_command: run-all apply

