name: 'tg-issue-55'

on:
  workflow_dispatch:

env:
  tf_version: "1.5.1"
  tg_version: '0.77.22'
  working_dir: "tg-issue-55"

jobs:

  run:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: dump
        run: |
          env
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"

      - name: Plan
        uses: gruntwork-io/terragrunt-action@feat/switch-off-docker
        env:
          TRACE: "1"
          TERRAGRUNT_NON_INTERACTIVE: "true"
          INPUT_PRE_EXEC_1: "env"
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: "${{ env.working_dir }}"
          tg_command: plan -out ${{ runner.workspace }}/terragrunt.tfplan

      - name: Apply
        uses: gruntwork-io/terragrunt-action@feat/switch-off-docker
        env:
          TRACE: "1"
          TERRAGRUNT_NON_INTERACTIVE: "true"
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: "${{ env.working_dir }}"
          tg_command: >-
            apply -auto-approve ${{ runner.workspace }}/terragrunt.tfplan
            
