name: 'tg-run-all'

on:
  workflow_dispatch:

env:
  tf_version: "1.7.5"
  tg_version: "0.55.18"
  working_dir: "run-all"

jobs:

  run:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Plan
        uses: gruntwork-io/terragrunt-action@bug/action-permissions-67
        env:
          TRACE: "1"
          TERRAGRUNT_NON_INTERACTIVE: "true"
          INPUT_PRE_EXEC_1: "ls -lahrt"
          INPUT_POST_EXEC_1: "ls -lahrt"
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: "${{ env.working_dir }}"
          tg_command: run-all plan --terragrunt-log-level debug

