name: 'tg-ssh'

on:
  workflow_dispatch:

env:
  tf_version: "1.5.1"
  tg_version: "0.55.21"
  working_dir: "action-ssh-repo"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create directory to pass ssh-agent socket
        run: "mkdir -p /home/runner/work/_temp/_github_workflow"
        shell: bash

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"

        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan --terragrunt-log-level debug'